name: torchok
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=21.2.4
  - pydantic=1.8.2
  - pyyaml=5.4.1
  - pytorch=1.9.0
  - torchvision=0.10.0
  - cudatoolkit=11.1
  - pytorch-lightning=1.4.5
  - nvidia-apex=0.1
  - pandas=1.3.2
  - scikit-learn=0.24.2
  - faiss-cpu=1.7.1
  - seaborn=0.11.2
  - jupyterlab=3.1.10
  - boto3=1.17.93
  - mlflow=1.14.1
  - pymysql=1.0.2
  - pip:
      - rank_eval==0.0.1
      - torchmetrics==0.8.1
      - opencv-python==4.5.3.56
      - albumentations==1.0.3
      - sagemaker==2.59.1
      - parameterized==0.8.1
      - jedi==0.17.2
