task:
  name: ClassificationTask
  params:
    backbone_name: resnet18
    backbone_params:
      pretrained: true
      in_chans: 3
    pooling_name: CustomPooling
    head_name: ArcFaceHead
    head_params:
      out_features: &num_classes 12
  input_shapes: [[3, &height 224, &width 224]]

joint_loss:
  losses:
    - name: CrossEntropyLoss
      mapping:
          input: prediction
          target: target
        
optimization:
  - optimizer: 
      name: Adam
      params:
        lr: 0.0001
    scheduler:
      name: ExponentialLR
      params:
        gamma: 0.97

data:
  TRAIN:
    - dataset:
        name: ImageClassificationDataset
        params:
          data_folder: '/workdir/Stanford_Online_Products'
          csv_path: 'train.csv'
          num_classes: *num_classes
        transform:
          - name: Compose
            params:
              transforms:
                - &resize
                    name: Resize
                    params:
                      height: *height
                      width: *width
                - &normalize
                  name: Normalize
                  params:
                    mean: [ 0.485, 0.456, 0.406 ]
                    std: [ 0.229, 0.224, 0.225 ]
                - &totensor
                  name: ToTensorV2
                
      dataloader: &dataloader_params
        batch_size: 64
        num_workers: 4
        shuffle: True
  VALID:
    - dataset:
        name: ImageClassificationDataset
        params:
          data_folder: '/workdir/Stanford_Online_Products'
          csv_path: 'test.csv'
          num_classes: *num_classes
        transform:
          - name: Compose
            params:
              transforms:
                - *resize
                - *normalize
                - *totensor
      dataloader: 
        batch_size: 64
        num_workers: 4
        shuffle: False

trainer:
  gpus: [0]
  max_epochs: 10

log_dir: '/workdir/logs/sop_arcface/'
experiment_name: sop_arcface

checkpoint:
  monitor: train/Accuracy
  save_last: true
  mode: max

metrics:
  - name: Accuracy
    mapping: 
      preds: prediction
      target: target
